---
title: "Memo 10"
date: "August 17, 2018"
output: 
  pdf_document:
    highlight: haddock
    keep_tex: yes
    number_sections: yes
    toc: no
  html_document: 
    fig_caption: yes
    theme: journal
header-includes:
- \usepackage{graphics}
- \usepackage{float}
- \usepackage{longtable}
---
#Material covered this week
This week I replicated the Devereux, Griffith, and Simpson metric and compared it to the EG metric for agglomeration. I also analyzed every year from 2011 to 2015 using the DGS metric and started creating visualizations of nonprofit core codes over time.

#What I learned
The DGS and EG metrics are highly correlated for positive values and not correlated at all for negative values. Also, it seems that nonprofit core codes vary widely in their agglomeration/dispersion, with the majority of core codes showing little or no agglomeration or dispersion.


#Barriers
My inexperience with writing functions led to clunky, inelegant, and repetitive code. Otherwise, there were no major barriers. 

#Plan for next week
In the next week, I plan to:
\begin{itemize}
  \item{replicate the DGS coagglomeration metric}
  \item{understand both metrics better}
  \item{run a simulation of the EG metric with $x_i$ given exogenously}
\end{itemize}
 